configType = 'standard-overrides'
fundDevAccounts = true
l1ChainID = 11155111
l1ContractsLocator = 'file:////Users/snehkoul/Espresso/optimism-espresso-integration/packages/contracts-bedrock/forge-artifacts'
l2ContractsLocator = 'file:////Users/snehkoul/Espresso/optimism-espresso-integration/packages/contracts-bedrock/forge-artifacts'
opDeployerVersion = 'untagged-4c98df18-1776447376'
opcmAddress = '0x0dead0118ed1ce6ad508bcedceded7987fc0566b'

[[chains]]
  baseFeeVaultRecipient = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  chainFeesRecipient = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  daFootprintGasScalar = 0
  eip1559Denominator = 50
  eip1559DenominatorCanyon = 250
  eip1559Elasticity = 6
  espressoBatcher = '0x976EA74026E726554dB657fA54763abd0C3a0aa9'
  espressoEnabled = true
  gasLimit = 60000000
  id = '0x000000000000000000000000000000000000000000000000000000000153c16e'
  l1FeeVaultRecipient = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  minBaseFee = 0
  operatorFeeConstant = 0
  operatorFeeScalar = 0
  operatorFeeVaultRecipient = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  sequencerFeeVaultRecipient = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  useRevenueShare = true

  [chains.customGasToken]
    liquidityControllerOwner = '0x0000000000000000000000000000000000000000'

  [chains.dangerousAltDAConfig]
    daChallengeWindow = 6
    daCommitmentType = 'GenericCommitment'
    daResolveWindow = 1
    useAltDA = true

  [chains.roles]
    batcher = '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC'
    challenger = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    l1ProxyAdminOwner = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    l2ProxyAdminOwner = '0x2fc3ffc903729a0f03966b917003800b145f67f3'
    proposer = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
    systemConfigOwner = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    unsafeBlockSigner = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'

[globalDeployOverrides]
  dangerouslyAllowCustomDisputeParameters = true
  disputeGameFinalityDelaySeconds = 6
  faultGameClockExtension = 10800
  faultGameMaxClockDuration = 302400
  preimageOracleChallengePeriod = 0
  proofMaturityDelaySeconds = 12
