services:
  l1-data-init:
    image: busybox
    command: >
      sh -c '
        mkdir -p /deployment/l1-config /deployment/deployer
        chown -R ${U_ID:-1000}:${GID:-1000} /deployment
        '
    volumes:
      - ./deployment:/deployment

  l1-anvil:
      depends_on:
        l1-data-init:
          condition: service_completed_successfully
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "cast bn --rpc-url http://localhost:${L1_HTTP_PORT} > /dev/null 2>&1 || exit 1",
          ]
        interval: 3s
        timeout: 2s
        retries: 40
      image: ghcr.io/foundry-rs/foundry:v1.5.1
      entrypoint: ["sh", "-c"]
      command:
        - |
          anvil \
            --silent \
            --host 0.0.0.0 \
            --port ${L1_HTTP_PORT} \
            --chain-id ${L1_CHAIN_ID} \
            --block-time 3 \
            --slots-in-an-epoch 1 \
            --init /config/genesis.json \
            --timestamp $$(date +%s) \
            --disable-code-size-limit \
            --base-fee 1000000000 \
            --gas-limit 45000000
      volumes:
        - ./deployment/l1-config:/config:ro
      ports:
        - "${L1_HTTP_PORT}:${L1_HTTP_PORT}"

  l2-rollup:
    restart: on-failure
    pull_policy: never
    image: ${OP_GETH_IMAGE}
    environment:
      - MODE=rollup
      - L1_RPC=http://l1-anvil:${L1_HTTP_PORT:?err}
      - OP_RPC=http://op-geth-sequencer:${OP_HTTP_PORT}
    depends_on:
      l1-anvil:
        condition: service_healthy
      op-geth-sequencer:
        condition: service_healthy
    volumes:
      - l2-config:/config
      - ./deployment/deployer:/deployer:ro

  l2-genesis:
    restart: on-failure
    depends_on:
      l1-data-init:
        condition: service_completed_successfully
      l1-anvil:
              condition: service_healthy
    image: ${OP_GETH_IMAGE}
    pull_policy: never # built by op-geth-sequencer
    environment:
      - MODE=genesis
      - L1_RPC=http://l1-anvil:${L1_HTTP_PORT}
      - HOME=/tmp
    volumes:
      - l2-config:/config
      - ./deployment/deployer:/deployer:ro

  op-geth-verifier:
    profiles: ["verifier"]
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${OP_HTTP_PORT}"]
      interval: 3s
      timeout: 2s
      retries: 40
    image: ${OP_GETH_IMAGE}
    depends_on:
      l2-genesis:
        condition: service_completed_successfully
      l1-anvil:
        condition: service_healthy
    volumes:
      - l2-config:/config:ro
      - op-data-verifier:/data
    environment:
      L1_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_HTTP_PORT: ${OP_HTTP_PORT}
      OP_ENGINE_PORT: ${OP_ENGINE_PORT}
    ports:
      - "8547:${OP_HTTP_PORT}"
      - "8553:${OP_ENGINE_PORT}"

  op-node-verifier:
    profiles: ["verifier"]
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${VERIFIER_PORT}"]
      interval: 3s
      timeout: 2s
      retries: 40
    image: ${OP_NODE_IMAGE}
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-verifier:
        condition: service_started
      l1-anvil:
        condition: service_healthy
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-verifier:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: ${VERIFIER_PORT}
    ports:
      - "${VERIFIER_PORT}:${VERIFIER_PORT}"
    volumes:
      - l2-config:/config:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --l1.beacon.ignore
      - --p2p.disable=true

  op-geth-sequencer:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-seq:/data
    ports:
      - "${OP_HTTP_PORT}:${OP_HTTP_PORT}"
      - "${OP_ENGINE_PORT}:${OP_ENGINE_PORT}"

  op-node-sequencer:
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${ROLLUP_PORT}"]
      interval: 3s
      timeout: 3s
      retries: 40
    image: ${OP_NODE_IMAGE}
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-sequencer:
        condition: service_healthy
      l1-anvil:
        condition: service_healthy
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-sequencer:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: ${ROLLUP_PORT}
      OP_NODE_SAFEDB_PATH: /data/safedb
    ports:
      - "${ROLLUP_PORT}:${ROLLUP_PORT}"
      - "9003:9003/tcp"
      - "9003:9003/udp"
    volumes:
      - l2-config:/config:ro
      - /etc/localtime:/etc/localtime:ro
      - op-node-seq:/data
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --sequencer.enabled=true
      - --sequencer.use-finalized=true
      - --rpc.addr=0.0.0.0
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --l1.beacon.ignore
      - --p2p.listen.ip=0.0.0.0
      - --p2p.listen.tcp=9003
      - --p2p.listen.udp=9003
      - --p2p.sequencer.key=${OPERATOR_PRIVATE_KEY}

  op-node-peer-connector:
    image: alpine:3.19
    depends_on:
      op-node-sequencer:
        condition: service_healthy
      op-node-fullnode:
        condition: service_started
      op-node-fullnode-2:
        condition: service_started
      op-node-fullnode-3:
        condition: service_started
    restart: "no"
    entrypoint:
      - sh
      - -c
      - |
        apk add --no-cache curl jq > /dev/null
        sleep 5
        PEER_ID=$$(curl -sf -X POST http://op-node-sequencer:${ROLLUP_PORT}           -H 'Content-Type: application/json'           -d '{"jsonrpc":"2.0","method":"opp2p_self","params":[],"id":1}'           | jq -r '.result.peerID')
        MULTIADDR="/dns4/op-node-sequencer/tcp/9003/p2p/$$PEER_ID"
        echo "Connecting fullnodes to sequencer p2p: $$MULTIADDR"
        curl -sf -X POST http://op-node-fullnode:9548   -H 'Content-Type: application/json' -d "{\"jsonrpc\":\"2.0\",\"method\":\"opp2p_connectPeer\",\"params\":[\"$$MULTIADDR\"],\"id\":1}"
        curl -sf -X POST http://op-node-fullnode-2:9548 -H 'Content-Type: application/json' -d "{\"jsonrpc\":\"2.0\",\"method\":\"opp2p_connectPeer\",\"params\":[\"$$MULTIADDR\"],\"id\":1}"
        curl -sf -X POST http://op-node-fullnode-3:9548 -H 'Content-Type: application/json' -d "{\"jsonrpc\":\"2.0\",\"method\":\"opp2p_connectPeer\",\"params\":[\"$$MULTIADDR\"],\"id\":1}"

  op-geth-fullnode:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-fullnode:/data
    ports:
      - "${OP_FULL_HTTP_PORT}:${OP_HTTP_PORT}"
      - "${OP_FULL_ENGINE_PORT}:${OP_ENGINE_PORT}"

  op-geth-fullnode-2:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-fullnode-2:/data

  op-geth-fullnode-3:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-fullnode-3:/data

  op-node-fullnode:
    image: ${OP_NODE_IMAGE}
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-fullnode:
        condition: service_started
      l1-anvil:
        condition: service_started
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-fullnode:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: "9548"
    ports:
      - "9548:9548"
    volumes:
      - l2-config:/config:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --rpc.enable-admin=true
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --l1.beacon.ignore
      - --p2p.listen.ip=0.0.0.0
      - --p2p.listen.tcp=9004
      - --p2p.listen.udp=9004
      - --p2p.no-discovery
      - --p2p.sync.req-resp=true

  op-node-fullnode-2:
    image: ${OP_NODE_IMAGE}
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-fullnode-2:
        condition: service_started
      l1-anvil:
        condition: service_started
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-fullnode-2:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: "9548"
    volumes:
      - l2-config:/config:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --rpc.enable-admin=true
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --l1.beacon.ignore
      - --p2p.listen.ip=0.0.0.0
      - --p2p.listen.tcp=9004
      - --p2p.listen.udp=9004
      - --p2p.no-discovery
      - --p2p.sync.req-resp=true

  op-node-fullnode-3:
    image: ${OP_NODE_IMAGE}
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-fullnode-3:
        condition: service_started
      l1-anvil:
        condition: service_started
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-anvil:${L1_HTTP_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-fullnode-3:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: "9548"
    volumes:
      - l2-config:/config:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --rpc.enable-admin=true
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --l1.beacon.ignore
      - --p2p.listen.ip=0.0.0.0
      - --p2p.listen.tcp=9004
      - --p2p.listen.udp=9004
      - --p2p.no-discovery
      - --p2p.sync.req-resp=true

  fullnode-proxy-1:
    build:
      context: ../..
    pull_policy: build
    depends_on:
      op-geth-fullnode:
        condition: service_healthy
      op-node-fullnode:
        condition: service_started
      espresso-dev-node:
        condition: service_started
    ports:
      - "8557:8080"
    command:
      - --full-node-execution-rpc=http://op-geth-fullnode:${OP_HTTP_PORT}
      - --op.full-node-consensus-rpc=http://op-node-fullnode:9548
      - --l1-rpc=http://l1-anvil:${L1_HTTP_PORT}
      - --op.enable=true
      - --op.query-service-url=http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT}
      - --op.light-client-address=${ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS}
      - --op.batcher-address=${TEE_BATCHER_ADDRESS}
      - --op.batch-authenticator-address=${BATCH_AUTH_ADDR}
      - --initial-hotshot-height=1

  fullnode-proxy-2:
    build:
      context: ../..
    pull_policy: build
    depends_on:
      op-geth-fullnode-2:
        condition: service_healthy
      op-node-fullnode-2:
        condition: service_started
      espresso-dev-node:
        condition: service_started
    ports:
      - "8558:8080"
    command:
      - --full-node-execution-rpc=http://op-geth-fullnode-2:${OP_HTTP_PORT}
      - --op.full-node-consensus-rpc=http://op-node-fullnode-2:9548
      - --l1-rpc=http://l1-anvil:${L1_HTTP_PORT}
      - --op.enable=true
      - --op.query-service-url=http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT}
      - --op.light-client-address=${ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS}
      - --op.batcher-address=${TEE_BATCHER_ADDRESS}
      - --op.batch-authenticator-address=${BATCH_AUTH_ADDR}
      - --initial-hotshot-height=1

  fullnode-proxy-3:
    build:
      context: ../..
    pull_policy: build
    depends_on:
      op-geth-fullnode-3:
        condition: service_healthy
      op-node-fullnode-3:
        condition: service_started
      espresso-dev-node:
        condition: service_started
    ports:
      - "8559:8080"
    command:
      - --full-node-execution-rpc=http://op-geth-fullnode-3:${OP_HTTP_PORT}
      - --op.full-node-consensus-rpc=http://op-node-fullnode-3:9548
      - --l1-rpc=http://l1-anvil:${L1_HTTP_PORT}
      - --op.enable=true
      - --op.query-service-url=http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT}
      - --op.light-client-address=${ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS}
      - --op.batcher-address=${TEE_BATCHER_ADDRESS}
      - --op.batch-authenticator-address=${BATCH_AUTH_ADDR}
      - --initial-hotshot-height=1

  proxyd:
    image: ${PROXYD_IMAGE}
    depends_on:
      fullnode-proxy-1:
        condition: service_healthy
      fullnode-proxy-2:
        condition: service_healthy
      fullnode-proxy-3:
        condition: service_healthy
    ports:
      - "${PROXYD_PORT:-8556}:8545"
    volumes:
      - ./proxyd.toml:/etc/proxyd/proxyd.toml:ro

  op-batcher:
    image: ${OP_BATCHER_IMAGE}
    depends_on:
      l1-anvil:
        condition: service_healthy
      op-geth-sequencer:
        condition: service_started
      op-node-sequencer:
        condition: service_started
      espresso-dev-node:
        condition: service_started
      l2-genesis:
        condition: service_completed_successfully
      attestation-service-zk:
        condition: service_healthy
    environment:
      L1_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_BATCHER_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_BATCHER_L2_ETH_RPC: http://op-geth-sequencer:${OP_HTTP_PORT}
      OP_BATCHER_ROLLUP_RPC: http://op-node-sequencer:${ROLLUP_PORT}
      OP_BATCHER_ESPRESSO_URLS: http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT},http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT}
      OP_BATCHER_MAX_CHANNEL_DURATION: "32"
      OP_BATCHER_MAX_PENDING_TX: "32"
    volumes:
      - ./deployment/deployer:/deployer:ro
    command:
      - op-batcher
      - --espresso.enabled=true
      - --espresso.poll-interval=1s
      - --espresso.espresso-attestation-service=http://attestation-service-zk:${ESPRESSO_ATTESTATION_VERIFIER_PORT}
      - --espresso.light-client-addr=${ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS}
      - --espresso.testing-batcher-private-key=${OP_TESTING_BATCHER_PRIVATE_KEY:-$OPERATOR_PRIVATE_KEY}
      - --private-key=${OP_BATCHER_PRIVATE_KEY:-$TEE_BATCHER_PRIVATE_KEY}
      - --espresso.batch-authenticator-addr=${BATCH_AUTH_ADDR}
      - --max-channel-duration=2
      - --target-num-frames=1
      - --max-pending-tx=32
      - --data-availability-type=calldata
      - --rpc.enable-admin

  op-batcher-fallback:
    profiles: ["fallback"]
    image: ${OP_BATCHER_IMAGE}
    depends_on:
      l1-anvil:
        condition: service_healthy
      op-geth-sequencer:
        condition: service_started
      op-node-sequencer:
        condition: service_started
      l2-genesis:
        condition: service_completed_successfully
    environment:
      L1_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_BATCHER_L1_ETH_RPC: http://l1-anvil:${L1_HTTP_PORT}
      OP_BATCHER_L2_ETH_RPC: http://op-geth-sequencer:${OP_HTTP_PORT}
      OP_BATCHER_ROLLUP_RPC: http://op-node-sequencer:${ROLLUP_PORT}
      OP_BATCHER_MAX_CHANNEL_DURATION: "32"
      OP_BATCHER_MAX_PENDING_TX: "32"
    volumes:
      - ./deployment/deployer:/deployer:ro
    command:
      - op-batcher
      - --espresso.enabled=false
      - --private-key=${FALLBACK_BATCHER_PRIVATE_KEY}
      - --throttle.unsafe-da-bytes-lower-threshold=0
      - --max-channel-duration=2
      - --target-num-frames=1
      - --max-pending-tx=32
      - --data-availability-type=calldata
      - --rpc.enable-admin

  espresso-dev-node:
    image: ${ESPRESSO_DEV_NODE_IMAGE}
    depends_on:
      l1-anvil:
        condition: service_healthy
    ports:
      - "${ESPRESSO_SEQUENCER_API_PORT}:${ESPRESSO_SEQUENCER_API_PORT}"
      - "${ESPRESSO_DEV_NODE_PORT}:${ESPRESSO_DEV_NODE_PORT}"
      - "${ESPRESSO_BUILDER_PORT}:${ESPRESSO_BUILDER_PORT}"
    volumes:
      - espresso-data:/data
    env_file:
      - ./.env
    environment:
      RUST_LOG: warn
      ESPRESSO_DEV_NODE_L1_DEPLOYMENT: skip
      RUST_BACKTRACE: 1
      ESPRESSO_SEQUENCER_STORAGE_PATH: /data/espresso
      ESPRESSO_SEQUENCER_L1_PROVIDER: http://l1-anvil:${L1_HTTP_PORT}
      ESPRESSO_DEPLOYER_ACCOUNT_INDEX: 0
      ESPRESSO_DEV_NODE_EPOCH_HEIGHT: "4294967295"
      ESPRESSO_SEQUENCER_ETH_MNEMONIC: "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"

  attestation-service-zk:
    image: ghcr.io/espressosystems/attestation-verifier-zk:sha-0e987c3
    platform: linux/amd64
    ports:
      - "${ESPRESSO_ATTESTATION_VERIFIER_PORT}:${ESPRESSO_ATTESTATION_VERIFIER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '''cat < /dev/null > /dev/tcp/localhost/${ESPRESSO_ATTESTATION_VERIFIER_PORT}''' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 150s
    env_file:
      - ./.env
    environment:
      NETWORK_PRIVATE_KEY: "${ESPRESSO_ATTESTATION_VERIFIER_NETWORK_PRIVATE_KEY}"
      NETWORK_RPC_URL: "${ESPRESSO_ATTESTATION_VERIFIER_NETWORK_RPC_URL}"
      SP1_PROVER: "${ESPRESSO_ATTESTATION_VERIFIER_SP1_PROVER}"
      RPC_URL: "${ESPRESSO_ATTESTATION_VERIFIER_RPC_URL}"
      NITRO_VERIFIER_ADDRESS: "${ESPRESSO_ATTESTATION_VERIFIER_NITRO_VERIFIER_ADDRESS}"
      USE_DOCKER: "${ESPRESSO_ATTESTATION_VERIFIER_NETWORK_USE_DOCKER}"
      SKIP_TIME_VALIDITY_CHECK: "${ESPRESSO_ATTESTATION_VERIFIER_SKIP_TIME_VALIDITY_CHECK}"
      RUST_LOG: "${ESPRESSO_ATTESTATION_VERIFIER_RUST_LOG}"
      HOST: "${ESPRESSO_ATTESTATION_VERIFIER_HOST}"
      PORT: "${ESPRESSO_ATTESTATION_VERIFIER_PORT}"

volumes:
  l2-config:
  op-data-seq:
  op-data-verifier:
  op-data-fullnode:
  op-data-fullnode-2:
  op-data-fullnode-3:
  op-node-seq:
  espresso-data:
